param(
  [string]$GameName = "BloodyGoodCurry",
  [string]$Preset = "web-release-split",
  [string]$OutputRoot = "deploy\\cloudflare",
  [string]$DataBaseUrl = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-RepoRoot {
  return (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}

function Ensure-InsideRoot {
  param(
    [Parameter(Mandatory = $true)][string]$RootPath,
    [Parameter(Mandatory = $true)][string]$CandidatePath
  )

  $resolvedRoot = [System.IO.Path]::GetFullPath($RootPath)
  $resolvedCandidate = [System.IO.Path]::GetFullPath($CandidatePath)
  if (-not $resolvedRoot.EndsWith([System.IO.Path]::DirectorySeparatorChar)) {
    $resolvedRoot += [System.IO.Path]::DirectorySeparatorChar
  }

  if (-not $resolvedCandidate.StartsWith($resolvedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to operate outside repo root: $resolvedCandidate"
  }

  return $resolvedCandidate
}

function Reset-Directory {
  param(
    [Parameter(Mandatory = $true)][string]$RepoRoot,
    [Parameter(Mandatory = $true)][string]$TargetPath
  )

  $safeTarget = Ensure-InsideRoot -RootPath $RepoRoot -CandidatePath $TargetPath
  if (Test-Path -LiteralPath $safeTarget) {
    Remove-Item -LiteralPath $safeTarget -Recurse -Force
  }
  New-Item -ItemType Directory -Path $safeTarget -Force | Out-Null
}

function Escape-JavaScriptString {
  param([string]$Value)

  return ($Value -replace "\\", "\\\\") -replace "'", "\\'"
}

$repoRoot = Get-RepoRoot
$buildDir = Join-Path $repoRoot "build\$Preset\Sandbox"
$outputRootAbs = Ensure-InsideRoot -RootPath $repoRoot -CandidatePath (Join-Path $repoRoot $OutputRoot)
$pagesDir = Join-Path $outputRootAbs "pages"
$r2Dir = Join-Path $outputRootAbs "r2"

$sourceHtml = Join-Path $buildDir "$GameName.html"
$sourceJs = Join-Path $buildDir "$GameName.js"
$sourceWasm = Join-Path $buildDir "$GameName.wasm"
$sourceData = Join-Path $buildDir "$GameName.data"

foreach ($requiredPath in @($sourceHtml, $sourceJs, $sourceWasm, $sourceData)) {
  if (-not (Test-Path -LiteralPath $requiredPath)) {
    throw "Missing build output: $requiredPath`nRun build_web_html.bat $GameName $Preset noserve first."
  }
}

Reset-Directory -RepoRoot $repoRoot -TargetPath $pagesDir
Reset-Directory -RepoRoot $repoRoot -TargetPath $r2Dir

$pagesIndex = Join-Path $pagesDir "index.html"
$pagesGameHtml = Join-Path $pagesDir "$GameName.html"
$pagesJs = Join-Path $pagesDir "$GameName.js"
$pagesWasm = Join-Path $pagesDir "$GameName.wasm"
$pagesConfig = Join-Path $pagesDir "site-config.js"
$pagesHeaders = Join-Path $pagesDir "_headers"
$r2Data = Join-Path $r2Dir "$GameName.data"

$html = Get-Content -LiteralPath $sourceHtml -Raw
$scriptTagPattern = "<script>"
$scriptTagReplacement = "<script src=""site-config.js""></script><script>"
$scriptTagRegex = [regex]$scriptTagPattern
$patchedHtml = $scriptTagRegex.Replace($html, $scriptTagReplacement, 1)

if ($patchedHtml -eq $html) {
  throw "Failed to inject site-config.js into $sourceHtml"
}

$configValue = $DataBaseUrl.Trim()
if ($configValue) {
  $escapedUrl = Escape-JavaScriptString -Value $configValue
  $configBody = @(
    "// Generated by tools/prepare_cloudflare_web_deploy.ps1",
    "window.SOFASPUDS_DATA_BASE_URL = '$escapedUrl';",
    ""
  ) -join [Environment]::NewLine
} else {
  $configBody = @(
    "// Set this to your public R2 bucket URL, for example:",
    "// window.SOFASPUDS_DATA_BASE_URL = 'https://pub-xxxxxxxx.r2.dev';",
    "window.SOFASPUDS_DATA_BASE_URL = window.SOFASPUDS_DATA_BASE_URL || '';",
    ""
  ) -join [Environment]::NewLine
}

$headersBody = @(
  "/*",
  "  Cache-Control: public, max-age=0, must-revalidate",
  "",
  "/*.js",
  "  Cache-Control: public, max-age=31536000, immutable",
  "",
  "/*.wasm",
  "  Content-Type: application/wasm",
  "  Cache-Control: public, max-age=31536000, immutable",
  ""
) -join [Environment]::NewLine

Set-Content -LiteralPath $pagesIndex -Value $patchedHtml
Set-Content -LiteralPath $pagesGameHtml -Value $patchedHtml
Set-Content -LiteralPath $pagesConfig -Value $configBody
Set-Content -LiteralPath $pagesHeaders -Value $headersBody
Copy-Item -LiteralPath $sourceJs -Destination $pagesJs
Copy-Item -LiteralPath $sourceWasm -Destination $pagesWasm
Copy-Item -LiteralPath $sourceData -Destination $r2Data

$dataSizeMb = [math]::Round(((Get-Item -LiteralPath $sourceData).Length / 1MB), 2)

Write-Host "Prepared Cloudflare deploy folders:"
Write-Host "  Pages: $pagesDir"
Write-Host "  R2:    $r2Dir"
Write-Host ""
Write-Host "Files:"
Write-Host "  Pages/index.html"
Write-Host "  Pages/$GameName.html"
Write-Host "  Pages/$GameName.js"
Write-Host "  Pages/$GameName.wasm"
Write-Host "  Pages/site-config.js"
Write-Host "  R2/$GameName.data ($dataSizeMb MB)"
Write-Host ""
if ($configValue) {
  Write-Host "site-config.js already points to: $configValue"
} else {
  Write-Host "Set deploy/cloudflare/pages/site-config.js to your public R2 URL after upload."
}
